name: Keep ARQ worker awake

on:
  schedule:
    - cron: '2/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render Web Service
        run: |
          curl -s https://url-shortener-arq-worker.onrender.com/ > /dev/null
          echo "Successfully pinged url-shortener-arq-worker!"
